#!/usr/bin/python3
from __future__ import print_function
import click
import validators
import logging
import grpc
import crawler_pb2
import crawler_pb2_grpc




@click.command()
@click.option('-start')
@click.option('-stop')
@click.option('-list')
def main(start,stop,list):
	"""
	Simple crawler CLI
	"""
	optlist = []
	optlist.append(list) if list is not None else None
	optlist.append(stop) if stop is not None else None
	optlist.append(start) if start is not None else None
	if len(optlist) != 1:
		print ("Please use at least and no more than one option use --help for more info")
		return
	#call to gRPC server
	with grpc.insecure_channel('localhost:50051') as channel:
		stub = crawler_pb2_grpc.CrawlerStub(channel)
		site = optlist[0]
		if not validators.url(site):	
			print ("Please use a valid URL")
			return
		if(start):
			response = stub.start(crawler_pb2.Request(url=site))
			print (response)
		if(stop):
			response = stub.stop(crawler_pb2.Request(url=site))
			print (response)
		if(list):
			response = stub.list(crawler_pb2.Request(url=site))
			print (response)
if __name__ == "__main__":
	logging.basicConfig()
	main()
